import { SURVIVAL_WIKI_BGM, type SongComposition, type TrackData, type DeviceProfile, midiToFreq, createReverbImpulse, getNoiseBuffer } from './worldBgmScoreAs';
export class AudioEngine {
  private ctx: AudioContext | null = null;
  private isPlaying: boolean = false;
  private isPaused: boolean = false;
  private currentStep: number = 0;
  private bpm: number = 88;
  private transpose: number = 0;
  private loop: boolean = true;
  private deviceProfile: DeviceProfile = 'balanced';
  private masterGain: GainNode | null = null;
  private compressor: DynamicsCompressorNode | null = null;
  private reverbNode: ConvolverNode | null = null;
  private reverbGain: GainNode | null = null;
  private eqLow: BiquadFilterNode | null = null;
  private eqMid: BiquadFilterNode | null = null;
  private eqHigh: BiquadFilterNode | null = null;
  private eqHpf: BiquadFilterNode | null = null;
  private analyser: AnalyserNode | null = null;
  private scheduleTimer: number | null = null;
  private playbackStartTime: number = 0;
  private currentSong: SongComposition;
  private onStepChange?: (step: number, bar: number) => void;
  private onPlaybackEnd?: () => void;
  constructor(song: SongComposition) { this.currentSong = JSON.parse(JSON.stringify(song)); this.bpm = song.defaultBpm; }
  public async init() {
    if (this.ctx && this.ctx.state !== 'closed') { if (this.ctx.state === 'suspended') await this.ctx.resume(); return; }
    const AudioCtx = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
    this.ctx = new AudioCtx();
    this.analyser = this.ctx.createAnalyser(); this.analyser.fftSize = 256; this.analyser.smoothingTimeConstant = 0.82;
    this.masterGain = this.ctx.createGain(); this.masterGain.gain.setValueAtTime(0.85, this.ctx.currentTime);
    this.compressor = this.ctx.createDynamicsCompressor(); this.compressor.threshold.setValueAtTime(-14, this.ctx.currentTime); this.compressor.knee.setValueAtTime(10, this.ctx.currentTime); this.compressor.ratio.setValueAtTime(3.5, this.ctx.currentTime); this.compressor.attack.setValueAtTime(0.003, this.ctx.currentTime); this.compressor.release.setValueAtTime(0.15, this.ctx.currentTime);
    this.eqHpf = this.ctx.createBiquadFilter(); this.eqHpf.type = 'highpass'; this.eqHpf.frequency.setValueAtTime(35, this.ctx.currentTime);
    this.eqLow = this.ctx.createBiquadFilter(); this.eqLow.type = 'lowshelf'; this.eqLow.frequency.setValueAtTime(140, this.ctx.currentTime); this.eqLow.gain.setValueAtTime(0.5, this.ctx.currentTime);
    this.eqMid = this.ctx.createBiquadFilter(); this.eqMid.type = 'peaking'; this.eqMid.frequency.setValueAtTime(2600, this.ctx.currentTime); this.eqMid.Q.setValueAtTime(0.8, this.ctx.currentTime); this.eqMid.gain.setValueAtTime(1.5, this.ctx.currentTime);
    this.eqHigh = this.ctx.createBiquadFilter(); this.eqHigh.type = 'highshelf'; this.eqHigh.frequency.setValueAtTime(10000, this.ctx.currentTime); this.eqHigh.gain.setValueAtTime(1.0, this.ctx.currentTime);
    this.reverbNode = this.ctx.createConvolver(); this.reverbNode.buffer = createReverbImpulse(this.ctx, 1.6, 2.4);
    this.reverbGain = this.ctx.createGain(); this.reverbGain.gain.setValueAtTime(0.28, this.ctx.currentTime); this.reverbGain.connect(this.eqHpf); this.reverbNode.connect(this.reverbGain);
    this.eqHpf.connect(this.eqLow); this.eqLow.connect(this.eqMid); this.eqMid.connect(this.eqHigh); this.eqHigh.connect(this.compressor); this.compressor.connect(this.analyser); this.analyser.connect(this.masterGain); this.masterGain.connect(this.ctx.destination);
    this.applyDeviceProfile(this.deviceProfile);
  }
  public setStepCallback(cb: (step: number, bar: number) => void) { this.onStepChange = cb; }
  public setEndCallback(cb: () => void) { this.onPlaybackEnd = cb; }
  public getAnalyser(): AnalyserNode | null { return this.analyser; }
  public getBpm(): number { return this.bpm; }
  public setBpm(val: number) { this.bpm = Math.max(60, Math.min(140, val)); }
  public getTranspose(): number { return this.transpose; }
  public setTranspose(val: number) { this.transpose = Math.max(-12, Math.min(12, val)); }
  public getLoop(): boolean { return this.loop; }
  public setLoop(val: boolean) { this.loop = val; }
  public setMasterVolume(val: number) { if (this.masterGain && this.ctx) this.masterGain.gain.setValueAtTime(Math.max(0, Math.min(1, val)), this.ctx.currentTime); }
  public getDeviceProfile(): DeviceProfile { return this.deviceProfile; }
  public applyDeviceProfile(profile: DeviceProfile) {
    this.deviceProfile = profile; if (!this.ctx || !this.eqHpf || !this.eqLow || !this.eqMid || !this.eqHigh) return; const t = this.ctx.currentTime;
    if (profile === 'phone_speaker') { this.eqHpf.frequency.setValueAtTime(75,t); this.eqLow.gain.setValueAtTime(2,t); this.eqMid.frequency.setValueAtTime(2400,t); this.eqMid.gain.setValueAtTime(3.8,t); this.eqHigh.gain.setValueAtTime(2.2,t); }
    else if (profile === 'vintage_warm') { this.eqHpf.frequency.setValueAtTime(40,t); this.eqLow.gain.setValueAtTime(1.8,t); this.eqMid.frequency.setValueAtTime(1800,t); this.eqMid.gain.setValueAtTime(0.5,t); this.eqHigh.gain.setValueAtTime(-1.8,t); }
    else { this.eqHpf.frequency.setValueAtTime(35,t); this.eqLow.gain.setValueAtTime(0.5,t); this.eqMid.frequency.setValueAtTime(2600,t); this.eqMid.gain.setValueAtTime(1.5,t); this.eqHigh.gain.setValueAtTime(1,t); }
  }
  public getSong(): SongComposition { return this.currentSong; }
  public updateTrack(trackId: string, updates: Partial<TrackData>) { const track = this.currentSong.tracks.find((t)=>t.id===trackId); if (track) Object.assign(track,updates); }
  public async play(startFromStep: number = 0) { await this.init(); if (!this.ctx) return; if (this.ctx.state === 'suspended') await this.ctx.resume(); this.isPlaying=true; this.isPaused=false; this.currentStep=startFromStep; this.playbackStartTime=this.ctx.currentTime; this.startScheduler(); }
  public pause() { this.isPlaying=false; this.isPaused=true; if (this.scheduleTimer!==null) { window.clearTimeout(this.scheduleTimer); this.scheduleTimer=null; } }
  public stop() { this.isPlaying=false; this.isPaused=false; this.currentStep=0; if (this.scheduleTimer!==null) { window.clearTimeout(this.scheduleTimer); this.scheduleTimer=null; } if (this.onStepChange) this.onStepChange(0,0); }
  public seek(step: number) { const totalSteps=this.currentSong.totalBars*this.currentSong.stepsPerBar; this.currentStep=Math.max(0,Math.min(totalSteps-1,step)); if (this.isPlaying) { this.pause(); void this.play(this.currentStep); } else if (this.onStepChange) this.onStepChange(this.currentStep,Math.floor(this.currentStep/16)); }
  public getIsPlaying(): boolean { return this.isPlaying; }
  public getCurrentStep(): number { return this.currentStep; }
  private startScheduler() {
    if (!this.ctx || !this.isPlaying) return; const lookaheadMs=25,scheduleAheadSec=0.12,totalSteps=this.currentSong.totalBars*this.currentSong.stepsPerBar; let nextStepTime=this.ctx.currentTime; const stepDuration=60/this.bpm/4;
    const runner=()=>{ if(!this.ctx||!this.isPlaying)return; while(nextStepTime<this.ctx.currentTime+scheduleAheadSec){ this.scheduleNotesAtStep(this.currentStep,nextStepTime,stepDuration); const stepReport=this.currentStep,barReport=Math.floor(stepReport/this.currentSong.stepsPerBar); setTimeout(()=>{if(this.isPlaying&&this.onStepChange)this.onStepChange(stepReport,barReport);},Math.max(0,(nextStepTime-this.ctx.currentTime)*1000)); this.currentStep++; nextStepTime+=stepDuration; if(this.currentStep>=totalSteps){ if(this.loop)this.currentStep=0; else{this.stop(); if(this.onPlaybackEnd)this.onPlaybackEnd(); return;} } } this.scheduleTimer=window.setTimeout(runner,lookaheadMs); }; runner();
  }
  private scheduleNotesAtStep(step:number,time:number,stepDuration:number){
    if(!this.ctx||!this.eqHpf||!this.reverbNode)return; const hasSolo=this.currentSong.tracks.some((t)=>t.solo);
    for(const track of this.currentSong.tracks){ if(track.muted)continue; if(hasSolo&&!track.solo)continue; const notesToPlay=track.notes.filter((n)=>n.step===step); if(notesToPlay.length===0)continue; const trackGain=this.ctx.createGain(); trackGain.gain.setValueAtTime(track.volume,time); const panner=this.ctx.createStereoPanner(); panner.pan.setValueAtTime(track.pan,time); trackGain.connect(panner); panner.connect(this.eqHpf); if(track.reverbSend>0.05){const sendGain=this.ctx.createGain();sendGain.gain.setValueAtTime(track.reverbSend,time);trackGain.connect(sendGain);sendGain.connect(this.reverbNode);} for(const note of notesToPlay){const noteDurationSec=note.duration*stepDuration,velocity=(note.velocity??0.7)*(track.volume??1),pitch=note.pitch+(track.id!=='drums'?this.transpose:0);this.synthesizeInstrument(this.ctx,track.id,pitch,time,noteDurationSec,velocity,trackGain,note.type);}}
  }
  public synthesizeInstrument(ctx:BaseAudioContext,instrumentId:string,pitch:number,time:number,duration:number,velocity:number,destination:AudioNode,drumType?:string){switch(instrumentId){case'epiano':this.synthEPiano(ctx,pitch,time,duration,velocity,destination);break;case'synthBell':this.synthBell(ctx,pitch,time,duration,velocity,destination);break;case'guitar':this.synthGuitarPluck(ctx,pitch,time,duration,velocity,destination);break;case'synthPad':this.synthPad(ctx,pitch,time,duration,velocity,destination);break;case'bass':this.synthBass(ctx,pitch,time,duration,velocity,destination);break;case'drums':this.synthDrum(ctx,drumType||'snare',time,velocity,destination);break;}}
  private synthEPiano(ctx:BaseAudioContext,pitch:number,time:number,duration:number,velocity:number,dest:AudioNode){const freq=midiToFreq(pitch),carrier=ctx.createOscillator();carrier.type='sine';carrier.frequency.setValueAtTime(freq,time);const bodyOsc=ctx.createOscillator();bodyOsc.type='triangle';bodyOsc.frequency.setValueAtTime(freq,time);const modulator=ctx.createOscillator();modulator.type='sine';modulator.frequency.setValueAtTime(freq*3,time);const modGain=ctx.createGain(),modDepth=freq*(0.8+velocity*1.6);modGain.gain.setValueAtTime(modDepth,time);modGain.gain.exponentialRampToValueAtTime(0.001,time+Math.min(0.35,duration));modulator.connect(modGain);modGain.connect(carrier.frequency);const filter=ctx.createBiquadFilter();filter.type='lowpass';const cutoff=Math.min(12000,freq*(3+velocity*5));filter.frequency.setValueAtTime(cutoff,time);filter.frequency.exponentialRampToValueAtTime(Math.max(300,freq*1.5),time+duration);const amp=ctx.createGain();amp.gain.setValueAtTime(0.0001,time);amp.gain.linearRampToValueAtTime(velocity*0.45,time+0.006);amp.gain.exponentialRampToValueAtTime(velocity*0.28,time+0.25);amp.gain.setValueAtTime(velocity*0.28,time+Math.max(0.25,duration-0.1));amp.gain.exponentialRampToValueAtTime(0.0001,time+duration+0.2);const bodyGain=ctx.createGain();bodyGain.gain.setValueAtTime(velocity*0.22,time);carrier.connect(filter);bodyOsc.connect(bodyGain);bodyGain.connect(filter);filter.connect(amp);amp.connect(dest);carrier.start(time);bodyOsc.start(time);modulator.start(time);const stopTime=time+duration+0.25;carrier.stop(stopTime);bodyOsc.stop(stopTime);modulator.stop(stopTime);}
  private synthBell(ctx:BaseAudioContext,pitch:number,time:number,duration:number,velocity:number,dest:AudioNode){const freq=midiToFreq(pitch),osc1=ctx.createOscillator();osc1.type='sine';osc1.frequency.setValueAtTime(freq,time);const osc2=ctx.createOscillator();osc2.type='sine';osc2.frequency.setValueAtTime(freq*2.76,time);const osc3=ctx.createOscillator();osc3.type='sine';osc3.frequency.setValueAtTime(freq*4.02,time);const amp=ctx.createGain();amp.gain.setValueAtTime(0.0001,time);amp.gain.linearRampToValueAtTime(velocity*0.32,time+0.015);amp.gain.exponentialRampToValueAtTime(0.0001,time+Math.max(0.8,duration*1.5));const g1=ctx.createGain(),g2=ctx.createGain(),g3=ctx.createGain();g1.gain.setValueAtTime(0.65,time);g2.gain.setValueAtTime(0.25,time);g3.gain.setValueAtTime(0.15,time);osc1.connect(g1);osc2.connect(g2);osc3.connect(g3);g1.connect(amp);g2.connect(amp);g3.connect(amp);amp.connect(dest);const stopTime=time+Math.max(1.2,duration*1.6);osc1.start(time);osc2.start(time);osc3.start(time);osc1.stop(stopTime);osc2.stop(stopTime);osc3.stop(stopTime);}
  private synthGuitarPluck(ctx:BaseAudioContext,pitch:number,time:number,duration:number,velocity:number,dest:AudioNode){const freq=midiToFreq(pitch),osc=ctx.createOscillator();osc.type='triangle';osc.frequency.setValueAtTime(freq,time);const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(Math.min(6500,freq*4.5),time);filter.frequency.exponentialRampToValueAtTime(freq*1.2,time+0.35);const amp=ctx.createGain();amp.gain.setValueAtTime(0.0001,time);amp.gain.linearRampToValueAtTime(velocity*0.45,time+0.008);amp.gain.exponentialRampToValueAtTime(velocity*0.15,time+0.3);amp.gain.exponentialRampToValueAtTime(0.0001,time+duration+0.1);osc.connect(filter);filter.connect(amp);amp.connect(dest);osc.start(time);osc.stop(time+duration+0.15);}
  private synthPad(ctx:BaseAudioContext,pitch:number,time:number,duration:number,velocity:number,dest:AudioNode){const freq=midiToFreq(pitch),osc1=ctx.createOscillator();osc1.type='sawtooth';osc1.frequency.setValueAtTime(freq*0.998,time);const osc2=ctx.createOscillator();osc2.type='sawtooth';osc2.frequency.setValueAtTime(freq*1.002,time);const osc3=ctx.createOscillator();osc3.type='triangle';osc3.frequency.setValueAtTime(freq,time);const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.Q.setValueAtTime(1.4,time);filter.frequency.setValueAtTime(600,time);filter.frequency.linearRampToValueAtTime(1400,time+duration*0.4);filter.frequency.linearRampToValueAtTime(750,time+duration);const amp=ctx.createGain();amp.gain.setValueAtTime(0.0001,time);amp.gain.linearRampToValueAtTime(velocity*0.25,time+0.22);amp.gain.setValueAtTime(velocity*0.25,time+Math.max(0.22,duration-0.3));amp.gain.exponentialRampToValueAtTime(0.0001,time+duration+0.4);osc1.connect(filter);osc2.connect(filter);osc3.connect(filter);filter.connect(amp);amp.connect(dest);const stopTime=time+duration+0.45;osc1.start(time);osc2.start(time);osc3.start(time);osc1.stop(stopTime);osc2.stop(stopTime);osc3.stop(stopTime);}
  private synthBass(ctx:BaseAudioContext,pitch:number,time:number,duration:number,velocity:number,dest:AudioNode){const freq=midiToFreq(pitch),subOsc=ctx.createOscillator();subOsc.type='sine';subOsc.frequency.setValueAtTime(freq,time);const midOsc=ctx.createOscillator();midOsc.type='triangle';midOsc.frequency.setValueAtTime(freq*2,time);const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(freq*3.5,time);filter.frequency.exponentialRampToValueAtTime(freq*1.8,time+0.25);const amp=ctx.createGain();amp.gain.setValueAtTime(0.0001,time);amp.gain.linearRampToValueAtTime(velocity*0.55,time+0.008);amp.gain.exponentialRampToValueAtTime(velocity*0.35,time+0.3);amp.gain.setValueAtTime(velocity*0.35,time+Math.max(0.3,duration-0.08));amp.gain.exponentialRampToValueAtTime(0.0001,time+duration+0.12);const subGain=ctx.createGain(),midGain=ctx.createGain();subGain.gain.setValueAtTime(0.7,time);midGain.gain.setValueAtTime(0.35,time);subOsc.connect(subGain);midOsc.connect(midGain);subGain.connect(filter);midGain.connect(filter);filter.connect(amp);amp.connect(dest);const stopTime=time+duration+0.15;subOsc.start(time);midOsc.start(time);subOsc.stop(stopTime);midOsc.stop(stopTime);}
  private synthDrum(ctx:BaseAudioContext,type:string,time:number,velocity:number,dest:AudioNode){const noiseBuffer=getNoiseBuffer(ctx);if(type==='kick'){const osc=ctx.createOscillator();osc.type='sine';osc.frequency.setValueAtTime(130,time);osc.frequency.exponentialRampToValueAtTime(45,time+0.09);const amp=ctx.createGain();amp.gain.setValueAtTime(velocity*0.75,time);amp.gain.exponentialRampToValueAtTime(0.001,time+0.22);osc.connect(amp);amp.connect(dest);osc.start(time);osc.stop(time+0.25);}else if(type==='snare'){const noise=ctx.createBufferSource();noise.buffer=noiseBuffer;const noiseFilter=ctx.createBiquadFilter();noiseFilter.type='bandpass';noiseFilter.frequency.setValueAtTime(1900,time);noiseFilter.Q.setValueAtTime(1.2,time);const noiseAmp=ctx.createGain();noiseAmp.gain.setValueAtTime(velocity*0.35,time);noiseAmp.gain.exponentialRampToValueAtTime(0.001,time+0.16);const osc=ctx.createOscillator();osc.type='triangle';osc.frequency.setValueAtTime(180,time);osc.frequency.exponentialRampToValueAtTime(80,time+0.08);const oscAmp=ctx.createGain();oscAmp.gain.setValueAtTime(velocity*0.28,time);oscAmp.gain.exponentialRampToValueAtTime(0.001,time+0.1);noise.connect(noiseFilter);noiseFilter.connect(noiseAmp);noiseAmp.connect(dest);osc.connect(oscAmp);oscAmp.connect(dest);noise.start(time);osc.start(time);noise.stop(time+0.2);osc.stop(time+0.15);}else if(type==='rim'){const osc=ctx.createOscillator();osc.type='triangle';osc.frequency.setValueAtTime(860,time);const amp=ctx.createGain();amp.gain.setValueAtTime(velocity*0.3,time);amp.gain.exponentialRampToValueAtTime(0.001,time+0.05);osc.connect(amp);amp.connect(dest);osc.start(time);osc.stop(time+0.06);}else if(type==='hihat'){const noise=ctx.createBufferSource();noise.buffer=noiseBuffer;const filter=ctx.createBiquadFilter();filter.type='highpass';filter.frequency.setValueAtTime(7500,time);const amp=ctx.createGain();amp.gain.setValueAtTime(velocity*0.22,time);amp.gain.exponentialRampToValueAtTime(0.001,time+0.045);noise.connect(filter);filter.connect(amp);amp.connect(dest);noise.start(time);noise.stop(time+0.06);}else if(type==='shaker'){const noise=ctx.createBufferSource();noise.buffer=noiseBuffer;const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.setValueAtTime(5800,time);filter.Q.setValueAtTime(2,time);const amp=ctx.createGain();amp.gain.setValueAtTime(0.001,time);amp.gain.linearRampToValueAtTime(velocity*0.18,time+0.02);amp.gain.exponentialRampToValueAtTime(0.001,time+0.08);noise.connect(filter);filter.connect(amp);amp.connect(dest);noise.start(time);noise.stop(time+0.09);}}
}
export const worldAudioEngine = new AudioEngine(SURVIVAL_WIKI_BGM);