export interface SoundCandidate {
  id: string;
  category: 'system' | 'screen' | 'action' | 'wiki';
  categoryJa: string;
  name: string;
  nameJa: string;
  description: string;
  toneInfo: string;
  keyCharacteristic: string;
}

export const SOUND_CANDIDATES: SoundCandidate[] = [
  {
    id: 'cursor_move',
    category: 'system',
    categoryJa: 'システム操作音',
    name: 'Cursor Move Tick',
    nameJa: 'カーソル移動・選択音',
    description: 'リストやスロットを選択・ホバーした際の非常に軽快で耳触りの良い16bitパルス音。',
    toneInfo: '800Hz / Sine-Square hybrid / 20ms',
    keyCharacteristic: '連打しても耳が疲れない微細アタック設計。',
  },
  {
    id: 'confirm',
    category: 'system',
    categoryJa: 'システム操作音',
    name: 'Primary Confirm Chime',
    nameJa: '決定・コマンド実行音',
    description: 'ボタン押下やスロットロード時の心地よい高域アルペジオ。',
    toneInfo: 'D5-A5-D6 / Square Wave / 150ms',
    keyCharacteristic: '16bitゲーム黄金期を彷彿とさせるクリアな高揚感。',
  },
  {
    id: 'cancel',
    category: 'system',
    categoryJa: 'システム操作音',
    name: 'Cancel & Dismiss Blip',
    nameJa: 'キャンセル・戻る音',
    description: 'モーダルを閉じる際や直前の階層へ戻る際の下降2音トーン。',
    toneInfo: 'E5->A4 / Square Wave / 120ms',
    keyCharacteristic: '視覚的バック演出と同期する確かなフィードバック。',
  },
  {
    id: 'warning',
    category: 'system',
    categoryJa: 'システム操作音',
    name: 'System Alert Buzz',
    nameJa: '警告・削除アラート音',
    description: '削除確認モーダルや入力エラー時の低音警告パルス。',
    toneInfo: '220Hz->200Hz / Sawtooth / 80ms x2',
    keyCharacteristic: '緊張感を走らせるレトロなノイズバズ。',
  },
  {
    id: 'tab_switch',
    category: 'screen',
    categoryJa: '画面・ナビゲーション音',
    name: 'Tab Switch Slide',
    nameJa: 'ページ・タブ切替音',
    description: '「ロケーション」「タイムライン」「Wiki」タブを切り替える際の軽快なスライド音。',
    toneInfo: '440Hz->660Hz / Triangle / 60ms',
    keyCharacteristic: 'ページが小気味よくめくられるような質感。',
  },
  {
    id: 'modal_open_close',
    category: 'screen',
    categoryJa: '画面・ナビゲーション音',
    name: 'Modal Expansion Chime',
    nameJa: 'モーダル展開音',
    description: 'ウィンドウが中央からポップアップする際の上昇トーン。',
    toneInfo: '320Hz->740Hz / Triangle / 100ms',
    keyCharacteristic: 'ウィンドウの拡大スケールアニメーションと同期。',
  },
  {
    id: 'dialogue_char',
    category: 'action',
    categoryJa: 'キャラクター＆アクション音',
    name: 'Dialogue Typewriter Click',
    nameJa: '語り部セリフ音',
    description: 'ウタペディアや語り部のセリフが1文字ずつ表示される際のレトロピコ音。',
    toneInfo: '520Hz->620Hz / Fast pulse / 30ms',
    keyCharacteristic: 'NPCごとの個性を際立たせる16bitボイスシミュレーション。',
  },
  {
    id: 'new_record',
    category: 'action',
    categoryJa: 'キャラクター＆アクション音',
    name: 'New Record Saved Fanfare',
    nameJa: '新規記録・セーブ完了音',
    description: 'ロケーションやワールドが新しく冒険の書に刻まれた瞬間のファンファーレ。',
    toneInfo: 'C5-E5-G5-C6 / Chord Arpeggio / 250ms',
    keyCharacteristic: 'プレイヤーの探検達成感を讃える明るいメロディ。',
  },
  {
    id: 'chest_open',
    category: 'action',
    categoryJa: 'キャラクター＆アクション音',
    name: 'Treasure Chest Open Fanfare',
    nameJa: '宝箱コレクション開封音',
    description: '写真コレクションや宝箱を開放した時のドラマチックなファンファーレ。',
    toneInfo: 'A4-C#5-E5-A5-C#6-E6 / Triangle / 400ms',
    keyCharacteristic: 'アイテム獲得の歓びを増幅するクラシックなRPGジングル。',
  },
  {
    id: 'achievement',
    category: 'action',
    categoryJa: 'キャラクター＆アクション音',
    name: 'Milestone Achievement Unlock',
    nameJa: 'マイルストーン達成音',
    description: 'タイムラインで特定の日数（3日目、7日目、30日目）を達成した時のクラウン音。',
    toneInfo: 'G5-C6-E6-G6 / High Sparkle / 450ms',
    keyCharacteristic: 'サバイバル生存記念バースト演出と同期。',
  },
  {
    id: 'wiki_generating_noise',
    category: 'wiki',
    categoryJa: 'Wiki編纂・AI演出音',
    name: 'Wiki AI Matrix Computing',
    nameJa: '旅の書AI編纂ノイズ',
    description: 'AIが過去の記録を解析・統合して記事を編纂している最中のサイバー通信音。',
    toneInfo: 'Filter Sweep White Noise + 1200Hz Bleeps / 300ms',
    keyCharacteristic: '知覚的サイバー空間の演算プロセスを音響化。',
  },
  {
    id: 'wiki_complete',
    category: 'wiki',
    categoryJa: 'Wiki編纂・AI演出音',
    name: 'Chronicle Finalized Chime',
    nameJa: '旅の書完成チャイム',
    description: 'Wiki記事の執筆が完了し、ウタペディアに登録された瞬間の重厚な鐘・チャイム。',
    toneInfo: '440Hz + 880Hz + 1320Hz / Bell Overtones / 800ms',
    keyCharacteristic: '歴史の1ページが刻まれたことを示す厳かな響き。',
  },
];
