export type SoundCandidateCategory =
  | 'system'
  | 'screen'
  | 'action'
  | 'wiki'
  | 'new_high'
  | 'new_medium'
  | 'npc_bgm';

export type PriorityLevel = '★★★' | '★★' | '★';

export interface NPCPersona {
  roleName: string;
  characterQuote: string;
  archetype: string;
  atmosphere: string;
  tempo: string;
  musicalTraits: string[];
}

export interface SoundCandidate {
  id: string;
  name: string;
  nameJa: string;
  category: SoundCandidateCategory;
  categoryJa: string;
  priority: PriorityLevel;
  usage: string;
  description: string;
  toneInfo: string;
  keyCharacteristic: string;
  isLooping?: boolean;
  isBgm?: boolean;
  isNew?: boolean;
  badgeType: 'existing' | 'new_high' | 'new_medium' | 'npc_bgm';
  npcPersona?: NPCPersona;
}

export const SOUND_CANDIDATES: SoundCandidate[] = [
  // ==========================================
  // 1. 既存音源 (12音 - 100%完全維持)
  // ==========================================
  {
    id: 'cursor_move',
    name: 'Cursor Move',
    nameJa: 'カーソル移動音',
    category: 'system',
    categoryJa: '既存システム・基本操作音',
    priority: '★★★',
    usage: 'リスト項目やボタン間のフォーカス移動時に鳴る、超低遅延なカーソル操作音。',
    description: '軽やかで快適な「ピコッ」。Switch風の素早いレスポンスと小気味よい高域のパルス。',
    toneInfo: 'Square (1320Hz → 1980Hz) / High-shelf Air / 45ms',
    keyCharacteristic: '短時間の高域ピッチスイープと繊細なリバーブで極めて低遅延な操作感を実現。',
    badgeType: 'existing',
  },
  {
    id: 'confirm',
    name: 'Confirm / Load',
    nameJa: '決定・ロード音',
    category: 'system',
    categoryJa: '既存システム・基本操作音',
    priority: '★★★',
    usage: 'ボタン押下・データ読み込み・主要アクション決定時のフィードバック音。',
    description: '芯のある「ピポッ」。明るい2音アルペジオで確実な決定フィードバックを提供。',
    toneInfo: 'Dual Square (A5 880Hz → A6 1760Hz) / Stereo Delay / 140ms',
    keyCharacteristic: 'ファミコンらしい矩形波の力強さにSwitch風の滑らかなディレイ残響をブレンド。',
    badgeType: 'existing',
  },
  {
    id: 'cancel',
    name: 'Cancel / Back',
    nameJa: 'キャンセル・戻る音',
    category: 'system',
    categoryJa: '既存システム・基本操作音',
    priority: '★★★',
    usage: 'ダイアログを閉じる・前画面へ戻る・操作を取り消す際のソフトなフィードバック音。',
    description: '低めの「ピピッ / ポッ」。耳に刺さらない柔らかな三角波と減衰ピッチ。',
    toneInfo: 'Square + Triangle (E5 659Hz → E4 330Hz) / 1.2kHz Lowpass / 110ms',
    keyCharacteristic: '丸みを帯びた下降ピッチで、誤操作感を与えない優しいキャンセル音。',
    badgeType: 'existing',
  },
  {
    id: 'warning',
    name: 'Warning / Delete',
    nameJa: '警告・削除音',
    category: 'system',
    categoryJa: '既存システム・基本操作音',
    priority: '★★★',
    usage: '危険な警告ダイアログの表示時やアイテム削除時の重厚なアラート音。',
    description: '重厚な「デンッ / ブブー」。不協和音デチューンとサブベースの低音アタック。',
    toneInfo: 'Detuned Saw/Square (Bb2 116Hz + B2 123Hz) + Sub Kick 65Hz / 280ms',
    keyCharacteristic: '警告・危険を瞬時に伝える重厚な低音キックとアナログレトロな歪み感。',
    badgeType: 'existing',
  },
  {
    id: 'tab_switch',
    name: 'Tab Switch',
    nameJa: 'タブ切り替え音',
    category: 'screen',
    categoryJa: '既存画面切替・演出音',
    priority: '★★★',
    usage: 'メインナビゲーションのタブやサブタブを切り替えた際のスピーディな風切り音。',
    description: 'サッとした「ピコッ」。風切りノイズと透明感のある高音パルスの融合。',
    toneInfo: 'Square Pitch Slide (950Hz → 1600Hz) + Bandpass Air Noise / 55ms',
    keyCharacteristic: '風を切るような微小ノイズを重ね、画面スライドの物理的な軽やかさを表現。',
    badgeType: 'existing',
  },
  {
    id: 'modal_open_close',
    name: 'Modal Open / Close',
    nameJa: 'モーダル開閉音',
    category: 'screen',
    categoryJa: '既存画面切替・演出音',
    priority: '★★★',
    usage: '設定モーダルや確認ウィンドウが画面中央にポップアップ/閉じる際のハプティクス音。',
    description: '心地よい「トンッ」。モダンUIの触感（ハプティクス）を思わせるポップな低域。',
    toneInfo: 'Sine Pitch Drop (480Hz → 110Hz) + Resonant Click / 120ms',
    keyCharacteristic: 'Switchのメニュー展開のような、丸く弾むポップなアタック感。',
    badgeType: 'existing',
  },
  {
    id: 'dialogue_char',
    name: 'Dialogue Character Blip',
    nameJa: 'キャラセリフ表示音',
    category: 'screen',
    categoryJa: '既存画面切替・演出音',
    priority: '★★★',
    usage: 'NPCセリフやテキストタイピング演出時に1文字ずつ連続で鳴るレトロドット音。',
    description: 'レトロRPG風「ポポポポポ…」。テキスト送り1文字ごとのドット音。',
    toneInfo: 'Triangle (880Hz ± Jitter) / Snappy Envelope / 35ms',
    keyCharacteristic: '長時間の文字送りでも耳が疲れない温かな三角波とわずかなピッチの揺らぎ。',
    badgeType: 'existing',
  },
  {
    id: 'new_record',
    name: 'New Record / Discovery',
    nameJa: '新規記録音',
    category: 'action',
    categoryJa: '既存アクション・体験音',
    priority: '★★★',
    usage: '新ロケーション初到達やタイムライン新規マイルストーン記録時の煌めく祝福音。',
    description: '爽快な「ピキーン！」。超高域クリスタルアルペジオと煌めくレゾナンス。',
    toneInfo: 'Triple Square Sweep (E6 → A6 → E7) + Shimmer 3.5kHz / 480ms',
    keyCharacteristic: 'ハイスコアや新アイテム発見を祝う、突き抜けるような高域の透明感。',
    badgeType: 'existing',
  },
  {
    id: 'chest_open',
    name: 'Chest Open',
    nameJa: 'チェスト開閉音',
    category: 'action',
    categoryJa: '既存アクション・体験音',
    priority: '★★★',
    usage: 'アイテムチェスト・インベントリ・保管庫の蓋を開けた際のギミック音。',
    description: '木箱が開く「パカッ」。ノック音、木の胴鳴り、チャイムの3層サウンド。',
    toneInfo: 'Layered Wood Click + Triangle Resonator (260Hz) + Chime (C5 → C6) / 200ms',
    keyCharacteristic: '宝箱や木箱の蓋が持ち上がる立体的なメカニカル感と期待感。',
    badgeType: 'existing',
  },
  {
    id: 'achievement',
    name: 'Achievement Unlocked',
    nameJa: '実績達成音',
    category: 'action',
    categoryJa: '既存アクション・体験音',
    priority: '★★★',
    usage: '実績アンロック・トロフィー獲得・重要クエスト達成時の凱旋ファンファーレ。',
    description: 'テンションの上がる「ティロリローン！」。凱旋の5音ファンファーレ。',
    toneInfo: '5-Note Major Arpeggio (C5-E5-G5-B5-C6-E6) + Wide Stereo Reverb / 600ms',
    keyCharacteristic: '16-bit黄金期のRPGを彷彿とさせる輝かしいアルペジオとモダンリバーブ。',
    badgeType: 'existing',
  },
  {
    id: 'wiki_generating_noise',
    name: 'Wiki Generating Noise',
    nameJa: 'Wiki生成中ノイズ',
    category: 'wiki',
    categoryJa: '既存生成・解析演出音',
    priority: '★★★',
    usage: 'AI Wiki記事を解析・生成している最中に背後で持続再生する環境音（ループ対応）。',
    description: 'CRT走査線風の連続環境音「ジー…」。走査線ノイズとCPU処理の電子つぶやき。',
    toneInfo: 'Bandpass CRT Raster Noise (1.45kHz) + 60Hz Power Hum + Digital Pulses (Loop)',
    keyCharacteristic: 'ON/OFFトグルでシームレスループ。データ解析中やAI生成中の心地よいレトロ環境音。',
    isLooping: true,
    badgeType: 'existing',
  },
  {
    id: 'wiki_complete',
    name: 'Wiki Complete / Book Finished',
    nameJa: 'Wiki完成音',
    category: 'wiki',
    categoryJa: '既存生成・解析演出音',
    priority: '★★★',
    usage: 'Wiki記事の生成が完了し、画面に美しく描画された瞬間のドラマチックなハープ音。',
    description: '冒険の書が完成した感動的な「ピロリロリーン！」。ハープ風の上昇グリッサンド。',
    toneInfo: '8-Note Major Pentatonic Harp Glissando (C5~G6) + Crystal Bell C7 (1.2s)',
    keyCharacteristic: '記事や本がパッと完成した瞬間を飾る、ドラマチックで神聖なアルペジオ。',
    badgeType: 'existing',
  },

  // ==========================================
  // 2. 新規SE候補：優先度【大】 (8音)
  // ==========================================
  {
    id: 'footstep',
    name: 'Footstep',
    nameJa: 'フットステップ音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★',
    usage: '画面内の移動・ナビゲーション操作など、歩行感を演出したい場面で使用する軽いステップ音。（※tab_switchとは別）',
    description: '乾いた地面を踏みしめるような「トッ / コッ」。三角波の低音パンチと極小の砂利ノイズ。',
    toneInfo: 'Low Triangle Punch (140Hz → 65Hz) + Soft Noise Filter (1.8kHz) / 65ms',
    keyCharacteristic: '連続移動で連打しても耳が疲れない、丸みと程よい硬さを持つリアルなステップ音。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'hover',
    name: 'Hover / Cursor Focus',
    nameJa: 'ホバー・フォーカス音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: 'アイコンやボタンにカーソルが乗った際、またはフォーカス時に鳴る極めて軽量なフィードバック音。',
    description: '触れた瞬間に光るような極小「チッ / プッ」。高域の澄んだマイクロパルス。',
    toneInfo: 'Ultra-fast Square Pulse (2200Hz) / Soft Gain / 22ms',
    keyCharacteristic: 'マウスを素早く動かしても不快な連打音にならず、UIの質感だけを高める空気のような軽量設計。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'card_open',
    name: 'Card Open',
    nameJa: 'カード・パネル展開音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: 'カードや詳細パネルを開く・アコーディオンを展開する際の、シャキッとした展開音。',
    description: 'スッと開く「シュパッ」。上昇レゾナンススイープとクリスプな立ち上がり。',
    toneInfo: 'Dual Square Sweep (520Hz → 1480Hz) + Resonant Air (4.2kHz) / 95ms',
    keyCharacteristic: 'カードが手前に立体的に飛び出してくるような視覚的快感と同期する、エッジの効いた展開音。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'card_close',
    name: 'Card Close',
    nameJa: 'カード・パネル収納音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: 'カードや詳細パネルを閉じる・アコーディオンを収納する際の、滑らかな閉じ音。',
    description: 'スッと収まる「シュポッ」。下降フィルターと柔らかな三角波の着地。',
    toneInfo: 'Triangle Pitch Drop (980Hz → 320Hz) + Lowpass Sweep (1.5kHz) / 85ms',
    keyCharacteristic: 'card_openと対になる音像。開く時よりもやや低く収束し、整然と閉じられた感覚を与える。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'add',
    name: 'Add Entry / Create',
    nameJa: '新規追加・登録音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: '新規データ登録・ロケーション追加・新しい要素をリストに加えた時の、明るく弾むエフェクト音。',
    description: 'ポンポンッと弾ける「ピポパッ！」。3連アップビートの爽快なメジャーアルペジオ。',
    toneInfo: '3-Step Square (G5 784Hz → C6 1046.5Hz → E6 1318.5Hz) / 130ms',
    keyCharacteristic: '何かが新しく誕生した喜びを感じさせる、軽快で弾力のある16bitポップサウンド。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'save',
    name: 'Save / Commit',
    nameJa: '保存完了音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: '編集内容の保存完了・データベース書き込み完了時に鳴る、確信の持てる澄んだ達成音。',
    description: 'スッキリ整う「ピンッ / チャイム」。高域の完全5度ハーモニーと穏やかなディレイ。',
    toneInfo: 'Harmonic Sine/Square (C6 1046.5Hz + G6 1568Hz) + Crystal Resonance / 240ms',
    keyCharacteristic: '「確実に保存された」という心理的安心感・安全感を与える、澄み切った高品位チャイム。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'toggle',
    name: 'Toggle Switch',
    nameJa: 'トグル・スイッチ切替音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: 'スイッチのON/OFF切り替え・チェックボックス・モード反転時の、パチッとしたレトロスイッチ音。',
    description: 'カチッと小気味よい「パチッ」。メカニカルなトグルスイッチのクリック感。',
    toneInfo: 'Dual Biquad Click (1800Hz / 850Hz) + Fast Square Transient / 40ms',
    keyCharacteristic: '物理的なトグルスイッチを跳ね上げたような、心地よい触感フィードバック。',
    isNew: true,
    badgeType: 'new_high',
  },
  {
    id: 'error',
    name: 'Error / Denied',
    nameJa: 'エラー・拒絶音',
    category: 'new_high',
    categoryJa: '新規SE候補【優先度：大】',
    priority: '★★★',
    usage: '入力不備・通信失敗・権限不足など、本当にエラーが発生した際に使用する、重厚だが不快すぎない警告音。',
    description: 'ズシッと重い「ブッブッ」。減衰する不協和ノコギリ波とローパス歪み。',
    toneInfo: 'Twin Sawtooth (F#3 185Hz + G3 196Hz) + Lowpass 900Hz / 220ms',
    keyCharacteristic: '不快な耳鳴りを避けつつ、操作が拒絶されたことを確実に伝えるコントロールされた重低音。',
    isNew: true,
    badgeType: 'new_high',
  },

  // ==========================================
  // 3. 新規SE候補：優先度【中】 (8音)
  // ==========================================
  {
    id: 'danger_confirm',
    name: 'Danger Confirm',
    nameJa: '危険操作・確認音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★★',
    usage: 'データ全削除・アカウントリセットなど、「危険な操作を実行する前の確認」を促す重厚な確認音。（※errorと明確に区別）',
    description: '緊張感走る「ドォン…ピキッ」。重厚なサブベースパルスと高域の警戒シマー。',
    toneInfo: 'Deep Sub Drop (90Hz → 45Hz) + Dual Detuned Square (D4/D#4) / 380ms',
    keyCharacteristic: 'プレイヤーに一度手を止めさせ、重大な決断を意識させる緊迫感のある低音ドラムロール。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'record_select',
    name: 'Record Select',
    nameJa: '記録・アイテム選択音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★★',
    usage: 'Timeline等の記録やサバイバル日誌の特定カードを選択・ハイライトした際に鳴る、軽いクリック音。',
    description: '乾いた「コツッ」。カセットテープやカードスロットを選択したような触感音。',
    toneInfo: 'Triangle Pluck (680Hz → 340Hz) + Wood Transient Filter / 50ms',
    keyCharacteristic: '日誌やレコードをめくるような自然な物理感があり、連続選択しても軽快。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'ai_generate_start',
    name: 'AI Generate Start',
    nameJa: 'AI生成開始・起動音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★★',
    usage: 'AI Wiki記事の生成開始時に鳴る、データ解析・システム起動を感じさせるサイバー音。',
    description: '電力が充填される「キュイィィン！」。高周波の上昇スイープとデジタルチャージ音。',
    toneInfo: 'Sawtooth Exponential Sweep (320Hz → 2400Hz) + Bitcrush Pulse / 320ms',
    keyCharacteristic: '巨大なスーパーコンピュータが起動してAIコアが計算を開始したようなサイバー感。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'ai_generate_complete',
    name: 'AI Generate Complete',
    nameJa: 'AI生成完了・祝福音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★★',
    usage: 'AI Wiki記事の生成完了時に鳴る、記事完成を祝福する幻想的なフィードバック音。',
    description: '光が拡散する「ティン・シャララ〜ン」。ホログラフィックな結晶音と空間残響。',
    toneInfo: 'Quad Square Harmony (E5-G#5-B5-E6) + Shimmer Delay / 750ms',
    keyCharacteristic: '高度なAI解析から結晶化された真実がWikiに刻印された瞬間を彩る、神聖で未来的な響き。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'chest_close',
    name: 'Chest Close',
    nameJa: 'チェスト収納・閉め音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★',
    usage: 'チェスト系UIや保管庫・ギャラリーを閉じる際の、「カチャン」という収納音。',
    description: '錠前がカチッと掛かる「ガチャン / カチッ」。木箱と金属ラッチの噛み合わせ。',
    toneInfo: 'Metal Latch Click (1.4kHz) + Wood Decay Box (180Hz) / 140ms',
    keyCharacteristic: 'chest_openの対。しっかりと蓋が閉まりアイテムが安全に保管された確信を与える。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'screen_transition',
    name: 'Screen Transition',
    nameJa: '大画面遷移・空間移動音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★',
    usage: 'ページ間の大きな画面遷移やワールド切替時に鳴る、空間が切り替わるようなディープな遷移音。',
    description: '空間がねじれる「フォシュゥゥン…」。深いバンドパスノイズとピッチドロップ。',
    toneInfo: 'Bandpass Noise Sweep (4.5kHz → 600Hz) + Sub Sine Body (85Hz) / 360ms',
    keyCharacteristic: 'UIの枠を超えて別の次元や別の記録層へ潜り込むような、シネマティックな没入感。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'notification',
    name: 'Notification Pop',
    nameJa: 'ポップアップ通知音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★★',
    usage: '保存完了・処理完了・トースト通知などの、ポップアップ通知に使用する短い通知音。',
    description: '愛らしい「ピロン♪」。高音2音の丸いベルチャイム。',
    toneInfo: 'Dual Sine / Soft Square (C6 1046.5Hz → E6 1318.5Hz) / 160ms',
    keyCharacteristic: '作業の集中を遮らず、画面の隅で控えめに発生したイベントを優しく知らせる。',
    isNew: true,
    badgeType: 'new_medium',
  },
  {
    id: 'input_focus',
    name: 'Input Focus',
    nameJa: '入力欄フォーカス音',
    category: 'new_medium',
    categoryJa: '新規SE候補【優先度：中】',
    priority: '★',
    usage: '入力欄や編集対象をクリック・フォーカスした際の、小さなパルス音。',
    description: '極小の「プッ」。編集モードへの切り替わりを伝える繊細なパルス。',
    toneInfo: 'Sine Micro-chirp (1600Hz → 800Hz) / 28ms',
    keyCharacteristic: 'テキスト入力を始める準備が整ったことを示す、邪魔にならない極小クリック。',
    isNew: true,
    badgeType: 'new_medium',
  },

  // ==========================================
  // 4. WIKI生成NPC 3人格専用BGM (3曲 - ループ対応)
  // ==========================================
  {
    id: 'npc_bgm_wikipedia',
    name: 'Encyclopedia Folklorist',
    nameJa: 'ウタペディア（百科事典・民俗学者）',
    category: 'npc_bgm',
    categoryJa: 'WIKI生成NPC専用BGM',
    priority: '★★★',
    usage: '「ウタペディア（百科事典・民俗学者）」記事閲覧・生成時の背景BGM。',
    description: 'クラシカル × レトロサイバー。几帳面なチェンバロ風アルペジオと不穏な半音階の揺らめき。',
    toneInfo: 'Square Harpsichord (A minor Arpeggio) + Polyphonic Triangle Bass + Digital Pulse Hum',
    keyCharacteristic: '学術的で整然としながらも、プレイヤーを知的に小馬鹿にするような冷ややかで不穏なバロック旋律。',
    isLooping: true,
    isBgm: true,
    isNew: true,
    badgeType: 'npc_bgm',
    npcPersona: {
      roleName: 'ウタペディア（百科事典・民俗学者）',
      characterQuote: '「ふむ、これがあなたの言う“生存記録”ですか。実に原始的で興味深い。せいぜい私の筆を鈍らせないことですな。」',
      archetype: '非常にプライドが高く皮肉屋な「天才民俗学者」',
      atmosphere: '学術的・客観的で整然としているが、どこか不穏。クラシカル × レトロサイバー × 洗練。',
      tempo: '112 BPM (Moderato Baroque)',
      musicalTraits: [
        'ハープシコード風16bit矩形波アルペジオ（Aマイナー主調）',
        '知的な冷徹さを表す整然とした8分音符シーケンス',
        '時折挟まれる不穏な減衰半音（ディミニッシュ和音）',
        '冷静沈着な通奏低音（Triangle Bass）',
      ],
    },
  },
  {
    id: 'npc_bgm_scp',
    name: 'SCP Foundation Senior Researcher',
    nameJa: 'SCP FOUNDATION（機密報告・特異点研究員）',
    category: 'npc_bgm',
    categoryJa: 'WIKI生成NPC専用BGM',
    priority: '★★★',
    usage: '「SCP FOUNDATION（機密報告・特異点研究員）」記事閲覧・生成時の背景BGM。',
    description: 'ミリタリー × サイバー × インダストリアル。重厚なインフラドローンと無機質なガイガーパルス。',
    toneInfo: 'Industrial Saw Bass (55Hz) + Geiger Noise Pulses + Metallic Filter Ping + Cold Lead',
    keyCharacteristic: '異常存在を隔離する冷酷な研究施設。プレイヤーをDクラス職員のように客観視する緊張感。',
    isLooping: true,
    isBgm: true,
    isNew: true,
    badgeType: 'npc_bgm',
    npcPersona: {
      roleName: 'SCP FOUNDATION（機密報告・特異点研究員）',
      characterQuote: '「対象のバイタル確認。異常性の発現ログを記録する。Dクラス、無駄な感情の表出は研究のノイズになる。」',
      archetype: '異常存在を調査・隔離する秘密組織の「冷徹な上級研究員」',
      atmosphere: '無機質・重厚・冷酷。ミリタリー × サイバー × インダストリアル 16bitアンビエント。',
      tempo: '96 BPM (Industrial Strict)',
      musicalTraits: [
        '重厚な低周波ノコギリ波ドローン（55Hz / A1）',
        'ガイガーカウンター風の不規則な微小ノイズパルス',
        '無機質で金属的な冷たいステップシーケンス',
        '感情を一切排除したミニマルなインターバル展開',
      ],
    },
  },
  {
    id: 'npc_bgm_ancient',
    name: 'Lost Chronicle Wandering Bard',
    nameJa: 'LOST CHRONICLE（絶望古文書・老吟遊詩人）',
    category: 'npc_bgm',
    categoryJa: 'WIKI生成NPC専用BGM',
    priority: '★★★',
    usage: '「LOST CHRONICLE（絶望古文書・老吟遊詩人）」記事閲覧・生成時の背景BGM。',
    description: 'レトロファンタジー × 16bitアンビエント。哀愁を帯びたマイナー旋律と滅びゆく世界の鐘。',
    toneInfo: 'Triangle Ancient Lute + Distant Tubular Bell + Ominous Wind Resonator + Minor Echoes',
    keyCharacteristic: '滅びゆく終末世界を記録し、プレイヤーの儚い足掻きを遠くから静かに嘲笑する美しくも哀しい旋律。',
    isLooping: true,
    isBgm: true,
    isNew: true,
    badgeType: 'npc_bgm',
    npcPersona: {
      roleName: 'LOST CHRONICLE（絶望古文書・老吟遊詩人）',
      characterQuote: '「ああ…またひとつ、灰となって消えゆく物語か。愚かな旅人よ、せめてこの古文書にその哀しき末路を刻んでやろう…」',
      archetype: '滅びゆく終末世界を記録する「老いた吟遊詩人」または「狂人の学者」',
      atmosphere: '悲壮感・哀愁・狂気。マイナー調を軸に、レトロファンタジー × 16bitアンビエント。',
      tempo: '78 BPM (Largo Elegiac)',
      musicalTraits: [
        '哀愁を帯びた三角波リュート（Eマイナーペンタトニック旋律）',
        '遠くの廃墟で打ち鳴らされるような不気味な鐘の響き',
        '滅びゆく風のようなアンビエント・レゾネーター',
        '狂気と美しさが交差する物悲しいドローンベース',
      ],
    },
  },
];
